version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpass
      POSTGRES_DB: walletdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: